set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_CROSSCOMPILING TRUE)
set(CROSS_COMPILE ON)

set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(GCC_COVERAGE_COMPILE_FLAGS "-D_SYS_BIOS -mfloat-abi=hard")
set(GCC_COVERAGE_LINK_FLAGS    "-lrdimon -lc -lc -lnosys")
set(CMAKE_C_FLAGS   "${GCC_COVERAGE_COMPILE_FLAGS}" CACHE STRING "toolchain_cflags" FORCE)
set(CMAKE_CXX_FLAGS "${GCC_COVERAGE_COMPILE_FLAGS}" CACHE STRING "toolchain_cxxflags" FORCE)
set(CMAKE_C_LINK_FLAGS   "${GCC_COVERAGE_LINK_FLAGS}")
set(CMAKE_CXX_LINK_FLAGS "${GCC_COVERAGE_LINK_FLAGS}")

set(CMAKE_BUILD_TYPE Release)
set(CMAKE_REQUIRED_LIBRARIES libnosys.a)
set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/../install.sysbios" CACHE STRING "llvm_sysbios_install" FORCE)

set(LLVM_TARGET_ARCH ARM)
set(LLVM_TARGETS_TO_BUILD ARM)
set(LLVM_DEFAULT_TARGET_TRIPLE "arm-none-eabi")
set(LLVM_ENABLE_RTTI ON)
set(LLVM_ENABLE_THREADS OFF CACHE BOOL "llvm_disable_threads" FORCE)
set(LLVM_NATIVE_BUILD "${CMAKE_BINARY_DIR}/build.native")
set(LLVM_TABLEGEN     "${CMAKE_BINARY_DIR}/build.native/bin/llvm-tblgen")
set(BUILD_SHARED_LIBS OFF)

set(BUILD_OS SYS_BIOS)

